# **Python indexing**

In [112]:
x = [1,2,3,4,5]
print(x[3])
print(x[-2])
print(x[2:5])
print(x[::2])
print(x[::-1])
print(x[5:2:-2])

# x[start : stop : step]

a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(a[1][2]) 


word = "MasteringPython"
print(word[9:])

nums = [10, 20, 30, 40, 50, 60, 70]
print(nums[5:2:-1])

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(alphabet[::2])



numbers = [10, 20, 30, 40, 50, 60]
numbers[1:3] =[90,100]
print(numbers)
numbers[2:4]=[]
print(numbers)


fruits = ["Apple", "Banana", "Cherry"]
print()
for index,fruit in enumerate(fruits):
    print(f"index no : {index} available fruit is {fruit}")

print()
for index,fruit in enumerate(fruits,start=1):
    print(f"in index {index} avilable fruit is : {fruit}")



print()
colors = ["Red", "Green", "Blue", "Yellow"]
pos = colors.index("Blue")
print(pos)


text = "Python"
new_text = "op " + text[:]
print(new_text)

data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print()
print(data[::2])
print(data[1::2])


print()
sentence = "I love Python programming"
new_sentence = sentence[2::2]
print(new_sentence)


## matrix[row_slice, col_slice]

matrix = np.array([
    [ 1,  2,  3,  4],   
    [ 5,  6,  7,  8],   
    [ 9, 10, 11, 12],   
    [13, 14, 15, 16]    
])
print(matrix[:1,:2])

print()
print(matrix[:1,:])
print(matrix[:,:1])
print()
print(matrix[1,:])
print(matrix[:,2])

print(matrix[0:2, 0:2])
print(matrix[0:2, 0:2])

print()
print(matrix[1:3, 1:3])
print()
print(matrix[::2, ::2])
print()
print(matrix[-2:, -2:])


#challenges
data = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200]
])
# [[ 80,  90],
#  [130, 140]]
print()
print(data[1:3,2:4])


temperatures = np.array([
    [22, 25, 28, 30],  
    [21, 24, 27, 32],  
    [23, 26, 29, 35],  
    [20, 22, 25, 28]   
])

print()
updated_temp = temperatures[2:,:]
print(updated_temp[updated_temp > 26])
print()
student = {"name": "Rahim", "age": 20, "grade": "A"}
print(student["name"]) 
print(student.get("city", "City Not Found"))

student["age"] = 21
student["city"] = "Dhaka" 
print(student.get("city", "City Not Found"))



data = {
    "Name": ["Rahim", "Karim", "Sumon", "Tina"],
    "Age": [22, 25, 21, 24],
    "City": ["Dhaka", "Chittagong", "Sylhet", "Dhaka"]
}

df = pd.DataFrame(data, index=["row1", "row2", "row3", "row4"])
print(df)
print()
print(df.iloc[0]) 
print()
print(df.iloc[1:3, 0:2]) 

print()
print(df.loc["row1", "Name"])
print(df.loc["row1":"row3", "Name":"Age"])

#challaeges
user_profile = {"username": "python_master", "status": "active"}
print(user_profile.get("pass","pass not found"))


products = pd.DataFrame({
    "Item": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1500, 12000],
    "Stock": [10, 50, 30, 15]
}, index=["P1", "P2", "P3", "P4"])
print(products.iloc[1:3,1:2])
print()

print(products.loc["P2":"P3" , "Item":"Price"])

4
4
[3, 4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]
[5]
6
Python
[60, 50, 40]
ACEGIKMOQSUWY
[10, 90, 100, 40, 50, 60]
[10, 90, 50, 60]

index no : 0 available fruit is Apple
index no : 1 available fruit is Banana
index no : 2 available fruit is Cherry

in index 1 avilable fruit is : Apple
in index 2 avilable fruit is : Banana
in index 3 avilable fruit is : Cherry

2
op Python

[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]

lv yhnpormig
[[1 2]]

[[1 2 3 4]]
[[ 1]
 [ 5]
 [ 9]
 [13]]

[5 6 7 8]
[ 3  7 11 15]
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]

[[ 6  7]
 [10 11]]

[[ 1  3]
 [ 9 11]]

[[11 12]
 [15 16]]

[[ 80  90]
 [130 140]]

[29 35 28]

Rahim
City Not Found
Dhaka
       Name  Age        City
row1  Rahim   22       Dhaka
row2  Karim   25  Chittagong
row3  Sumon   21      Sylhet
row4   Tina   24       Dhaka

Name    Rahim
Age        22
City    Dhaka
Name: row1, dtype: object

       Name  Age
row2  Karim   25
row3  Sumon   21

Rahim
       Name  Age
row1  Rahim   22
row2  Karim   25
row3  Sumon   21
pass not found
    P

In [114]:
import pandas as pd
import numpy as np

raw_data = """
ID:101 | Name:  _Rahim Ahmed_  | Price: 5000tk | Status: Active
ID:102 | Name: Karim_Hasan | Price: 12000tk | Status: Inactive
ID:103 | Name:   Tina   | Price: 8500tk | Status: Active
ID:104 | Name: Sumon_Bhai | Price: 3000tk | Status: Active
ID:105 | Name: _Missing_Data_ | Status: Active  
""" 

cleaned_records = []

for line in raw_data.strip().split('\n'):
    parts = line.split('|')
    
    record_id = parts[0].split(':')[1].strip()
    
    raw_name = parts[1].split(':')[1].strip()
    clean_name = raw_name.replace('_', ' ').strip()
    
    price_str = parts[2].split(':')[1].strip() if len(parts) > 2 else "0tk"
    
    clean_price = int(price_str[:-2]) if price_str.endswith('tk') else 0
    
    status_str = parts[3].split(':')[1].strip() if len(parts) > 3 else "Unknown"

    record = {
        "ID": record_id,
        "Name": clean_name,
        "Price": clean_price,
        "Status": status_str
    }
    cleaned_records.append(record)

print("✅ Cleaned dictionary list:")
for r in cleaned_records:
    print(r)

df = pd.DataFrame(cleaned_records).set_index("ID")
print("\n📊 Pandas DataFrame:")
print(df)

print("\n--- 4.1: Using .loc to get specific ID data ---")
print(df.loc["103", "Name":"Price"])

print("\n--- 4.2: Using .iloc for position-based data ---")
print(df.iloc[-2:, 0:2])

print("\n--- 4.3: Boolean Filtering ---")
active_high_value = df[(df["Status"] == "Active") & (df["Price"] > 4000)]
print(active_high_value)

print("\n--- 4.4: NumPy 2D Slicing Combo ---")
numpy_matrix = df[["Price", "Status"]].values
print("NumPy Array Slice (Last 3 rows, all cols):")
print(numpy_matrix[-3:, :])

✅ Cleaned dictionary list:
{'ID': '101', 'Name': 'Rahim Ahmed', 'Price': 5000, 'Status': 'Active'}
{'ID': '102', 'Name': 'Karim Hasan', 'Price': 12000, 'Status': 'Inactive'}
{'ID': '103', 'Name': 'Tina', 'Price': 8500, 'Status': 'Active'}
{'ID': '104', 'Name': 'Sumon Bhai', 'Price': 3000, 'Status': 'Active'}
{'ID': '105', 'Name': 'Missing Data', 'Price': 0, 'Status': 'Unknown'}

📊 Pandas DataFrame:
             Name  Price    Status
ID                                
101   Rahim Ahmed   5000    Active
102   Karim Hasan  12000  Inactive
103          Tina   8500    Active
104    Sumon Bhai   3000    Active
105  Missing Data      0   Unknown

--- 4.1: Using .loc to get specific ID data ---
Name     Tina
Price    8500
Name: 103, dtype: object

--- 4.2: Using .iloc for position-based data ---
             Name  Price
ID                      
104    Sumon Bhai   3000
105  Missing Data      0

--- 4.3: Boolean Filtering ---
            Name  Price  Status
ID                             
101  